#!/usr/bin/env bash
# ASDEV Agent Command Center — Collect agent report from output
# Takes a task output file and formats it as a PR report
# Usage: ./collect-agent-report.sh <task_id> <output_file> [--dry-run]
set -euo pipefail

DRY_RUN=false
[[ "${3:-}" == "--dry-run" ]] && DRY_RUN=true

if [[ $# -lt 2 ]]; then
  echo "Usage: $0 <task_id> <output_file> [--dry-run]"
  exit 1
fi

TASK_ID="$1"
OUTPUT_FILE="$2"

echo "ASDEV Collect Agent Report"
echo "Task: ${TASK_ID} | Output: ${OUTPUT_FILE}"
echo ""

if [[ ! -f "$OUTPUT_FILE" ]]; then
  echo "❌ Output file not found: ${OUTPUT_FILE}"
  exit 1
fi

# Generate report
REPORT_FILE="/tmp/asdev-report-${TASK_ID}.md"
cat > "${REPORT_FILE}" << REPORT_EOF
# Agent Execution Report — ${TASK_ID}

**Status:** Complete
**Task ID:** ${TASK_ID}
**Date:** $(date -u +"%Y-%m-%dT%H:%M:%SZ")

---

## Output

$(cat "${OUTPUT_FILE}")

---

## Validation

- Product repos touched: NONE
- PersianToolbox touched: NONE
- Deploy commands: NONE

---

*Generated by collect-agent-report.sh*
REPORT_EOF

if $DRY_RUN; then
  echo "[DRY-RUN] Would post report to PR #42"
  echo "Report file: ${REPORT_FILE}"
  echo ""
  cat "${REPORT_FILE}"
  exit 0
fi

echo "✅ Report generated: ${REPORT_FILE}"
echo ""
cat "${REPORT_FILE}"
