#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORKSPACE_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

TASK_ID="${1:-unknown}"
STATUS="${2:-success}"
SUMMARY="${3:-No summary provided}"

REPORT_DIR="${WORKSPACE_ROOT}/ops/automation-logs"
mkdir -p "$REPORT_DIR"

REPORT_FILE="${REPORT_DIR}/report-${TASK_ID}-$(date -u +%Y%m%d-%H%M%S).md"

cat > "$REPORT_FILE" <<EOF
# Agent Execution Report — ${TASK_ID}

**Status:** ${STATUS}
**Timestamp:** ${TIMESTAMP}
**Task:** ${TASK_ID}

## Summary

${SUMMARY}

## Validation

- Typecheck: $(cd "${WORKSPACE_ROOT}/sites/live/auditsystems" && pnpm typecheck 2>&1 | tail -1 && echo "PASS" || echo "FAIL")
- Lint: $(cd "${WORKSPACE_ROOT}/sites/live/auditsystems" && pnpm lint 2>&1 | tail -1 && echo "PASS" || echo "FAIL")
- Tests: $(cd "${WORKSPACE_ROOT}/sites/live/auditsystems" && pnpm test 2>&1 | tail -3 | head -1)

## Safety

- PersianToolbox: untouched
- Secrets: not exposed
- Deploy: not triggered
- Billing: not modified

---
*Generated by ASDEV Autonomous Execution Engine*
EOF

echo "Report written to: ${REPORT_FILE}"
