#!/usr/bin/env bash
set -euo pipefail

DOMAINS_DEFAULT="localhost,127.0.0.1,::1,alirezasafaeisystems.ir,.alirezasafaeisystems.ir,persiantoolbox.ir,.persiantoolbox.ir"
DOMAINS="${ASDEV_NO_PROXY_DOMAINS:-$DOMAINS_DEFAULT}"
ENV_FILE="$HOME/.config/asdev/proxy-policy.env"
ZSHRC="$HOME/.zshrc"
BASHRC="$HOME/.bashrc"
MARK_START="# >>> asdev proxy policy >>>"
MARK_END="# <<< asdev proxy policy <<<"

mkdir -p "$(dirname "$ENV_FILE")"

cat > "$ENV_FILE" <<POLICY
# Generated by apply-local-proxy-policy.sh
export NO_PROXY="$DOMAINS"
export no_proxy="$DOMAINS"
POLICY

inject_block() {
  local target="$1"
  [[ -f "$target" ]] || touch "$target"
  if grep -q "$MARK_START" "$target"; then
    awk -v s="$MARK_START" -v e="$MARK_END" '
      $0==s {skip=1; print s; system("cat \"'$ENV_FILE'\""); next}
      $0==e {skip=0; print e; next}
      !skip {print}
    ' "$target" > "$target.tmp"
    mv "$target.tmp" "$target"
  else
    {
      echo
      echo "$MARK_START"
      echo "[ -f \"$ENV_FILE\" ] && source \"$ENV_FILE\""
      echo "$MARK_END"
    } >> "$target"
  fi
}

inject_block "$ZSHRC"
inject_block "$BASHRC"

export NO_PROXY="$DOMAINS"
export no_proxy="$DOMAINS"

echo "Applied NO_PROXY policy."
echo "NO_PROXY=$NO_PROXY"
echo "Env file: $ENV_FILE"
